### ISSUE TITLE
Crash on Samsung S4 mini

### ISSUE THREAD

**Issue by consp1racy** [DreaminginCodeZH/MaterialProgressBar#47]
```
android.content.res.Resources$NotFoundException: File res/drawable-hdpi/tw_ic_menu_translate_holo_dark.spi from drawable resource ID #0x1080a78: .xml extension required
    at android.content.res.Resources.loadColorStateList(Resources.java:3632)
    at android.content.res.TypedArray.getColor(TypedArray.java:320)
    at me.zhanghai.android.materialprogressbar.internal.ThemeUtils.getColorFromAttrRes(ThemeUtils.java:18)
    at me.zhanghai.android.materialprogressbar.BaseIndeterminateProgressDrawable.<init>(BaseIndeterminateProgressDrawable.java:23)
    at me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable.<init>(IndeterminateProgressDrawable.java:38)
```

Maybe using `TintTypedArray` in `ThemeUtils` will help.

**Comment by consp1racy** [comment]
It didn't. This is library agnostic, sorry to bother you.
