### ISSUE TITLE
Crash on API 17 / Android 4.2

### ISSUE THREAD

**Issue by realdadfish** [DreaminginCodeZH/MaterialProgressBar#8]
When the Material Progress Bar is instantiated on API 17, this crash pops up (tested on API 17 emulator and older Samsung device):

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{my.package/my.package.ui.login.LoginActivity}: java.lang.NumberFormatException: Invalid int: ".0dip"
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
    at android.app.ActivityThread.access$600(ActivityThread.java:141)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5041)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NumberFormatException: Invalid int: ".0dip"
    at java.lang.Integer.invalidInt(Integer.java:138)
    at java.lang.Integer.parse(Integer.java:375)
    at java.lang.Integer.parseInt(Integer.java:366)
    at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:123)
    at android.content.res.TypedArray.getInt(TypedArray.java:254)
    at me.zhanghai.android.materialprogressbar.MaterialProgressBar.init(MaterialProgressBar.java:80)
    at me.zhanghai.android.materialprogressbar.MaterialProgressBar.<init>(MaterialProgressBar.java:39)
    at my.package.LoginActivity.onCreate(LoginActivity.java:54)
    at android.app.Activity.performCreate(Activity.java:5104)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
    ... 11 more
```

I debugged myself into the code but could not find the root source where this comes from. The value it apparently tries to parse is `0.0dip`, which is of course totally invalid for `android:tintMode`. Any clues here?

**Comment by zhanghai** [comment]
Please make sure that you are using the latest version `1.1.4` and verify if this is a duplicate of #6 .

**Comment by realdadfish** [comment]
Yep, 1.1.4 fixed the issue, sorry for the noise. Didn't saw a changelog or anything, so I was unaware of it.
